name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - run: cd ..
    - run: cd ..
    - run: cd ..
    - run: cd Api
    - run: npm install
    - run: npm run build
    - run: cd ..
    - run: cd client
    - run: npm install
    - run: npm run build